import pandas as pd
import numpy as np
import requests
from urllib.parse import urljoin
from bs4 import BeautifulSoup
import os
import time

base_directory = os.getcwd()

# from standard_charted_bank import *
pd.set_option("display.max_colwidth", 200)
columns_to_use = [
    "Bank Name",
    "Merchant Name",
    "Link to offer on Bank site (for reference)",
    "Category",
    "Offer title (if available)",
    "Start date",
    "End date",
    "Detailed offer text (if available)",
    "Logo link",
    "Offer image",
    "Redeem link",
    "Promo code (if available)",
    "Online/ Offline",
    "If offline, cities",
]
columns_to_use = [
    "Bank Name",
    "Merchant Name",
    "Link to offer on Bank site (for reference)",
    "Category",
    "Offer title (if available)",
    "Start date",
    "End date",
    "Detailed offer text (if available)",
    "Logo link",
    "Offer image",
    "Redeem link",
    "Promo code (if available)",
    "Online/ Offline",
    "If offline, cities",
]
brand_category_dict = {
    "Netmeds": "Healthcare", 
    "Tata 1mg": "Healthcare", 
    "Via.Com": "Travel", 
    "Myntra": "Fashion", 
    "ITC Store": "Retail", 
    "Fabhotels": "Hospitality", 
    "Onefinerate.Com": "Travel",
    "Ferns N Petals": "Gifts",
    "Ferns and Petals": "Gifts",
    "Beardo": "Personal Care", 
    "Thrive Co": "Health & Wellness", 
    "Lee": "Fashion", 
    "Ixigo": "Travel", 
    "Behrouz Biryani": "Food", 
    "Faasos": "Food",
    "St. Botanica": "Personal Care", 
    "Thyrocare": "Healthcare", 
    "Candy Floss": "Food", 
    "Myglamm": "Beauty", 
    "Sweet Truth": "Food", 
    "Rapido": "Transportation", 
    "Kalki Fashion": "Fashion",
    "Lifestyle": "Retail",
    "Firangi Bake": "Food",
    "The Good Bowl": "Food",
    "The Lunch Box": "Food",
    "Oven Story": "Food",
    "Eatsure": "Food",
    "Eat Sure":"Food",
    "Slay Coffee": "Food & Beverage",
    "Arata": "Personal Care",
    "Boheco Life": "Health & Wellness",
    "Healthkart": "Health & Fitness",
    "Pee Safe": "Personal Care",
    "Cityfurnish": "Furniture",
    "Daily Objects": "Accessories",
    "Matrix (Sim Cards)": "Telecommunications",
    "Matrix (Travel Insurance)": "Insurance",
    "Hype": "Fashion",
    "Fastrack": "Fashion",
    "Titan": "Fashion",
    "McCaffeine": "Personal Care",
    "Zingbus": "Transportation",
    "My Fitness": "Health & Fitness",
    "Macv": "Fashion",
    "Body Cupid": "Personal Care",
    "Wow Skin": "Personal Care",
    "Abhibus": "Transportation",
    "Lo Foods": "Food",
    "Fast&Up": "Health & Wellness",
    "Holiday Of Dreams": "Travel",
    "Igp": "Gifts",
    "Kidzania": "Entertainment",
    "Stayvista": "Hospitality",
    "Beyoung": "Fashion",
    "Mommypure": "Personal Care",
    "Leaf Studios": "Electronics",
    "Edureka": "Education",
    "Giva": "Gifts",
    "Zouk": "Fashion",
    "Medibuddy": "Healthcare",
    "Skullcandy": "Electronics",
    "Indus Health Plus": "Healthcare",
    "Khadi Naturals": "Personal Care",
    "Atulya Herbals": "Personal Care",
    "Tangyoak": "Food",
    "Desi Toys": "Toys & Games",
    "R For Rabbit": "Baby Products",
    "Clovia": "Fashion",
    "Kapiva": "Health & Wellness",
    "Rummy Circle": "Gaming",
    "Care Insurance": "Insurance",
    "Fitterfly": "Health & Wellness",
    "Sonata": "Fashion",
    "Uspa": "Fashion",
    "Nnnow": "Fashion",
    "Redcliffe Labs": "Healthcare",
    "Simple Skincare": "Personal Care",
    "Love, Beauty & Planet": "Personal Care",
    "Weber® – American Barbecue Grills And Accessories": "Home & Garden",
    "Musafir- Domestic Flight Bookings": "Travel",
    "Musafir-International Flight Bookings": "Travel",
    "Musafir-Dubai Visa": "Travel",
    "Ease My Trip": "Travel",
    "Acko Insurance": "Insurance",
    "Saffronstays": "Hospitality",
    "Yatra": "Travel",
    "Musafir": "Travel",
    "Sleepy Owl Coffee": "Food & Beverage",
    "Metro Shoes": "Fashion",
    "Mochi Shoes": "Fashion",
    "Imagicaa": "Entertainment",
    "Rideev": "Transportation",
    "Jaipur Rugs": "Home & Decor",
    "Celio": "Fashion",
    "Tattva Spa": "Health & Wellness",
    "Jar": "Home & Kitchen",
    "Find Your Happy Place": "Lifestyle",
    "Acnesquad": "Personal Care",
    "Livspace": "Home & Decor",
    "The Man Company": "Personal Care",
    "Muscletech": "Health & Fitness",
    "Cloudtailor": "Fashion",
    "Gaana Plus": "Entertainment",
    "Max Online (Offer 1)": "Retail",
    "Homecentre (Offer 1)": "Home & Decor",
    "Lenovo (Offer 1)": "Electronics",
    "Lenovo (Offer 2)": "Electronics",
    "Boat": "Electronics",
    "Jivisa": "Fashion",
    "Tupperware": "Kitchenware",
    "Wendy'S": "Food",
    "Max Online (Offer 2)": "Retail",
    "Koskii": "Fashion",
    "Knowledge Hut": "Education",
    "Woggles": "Fashion",
    "Happinetz": "Entertainment",
    "Salty": "Food",
    "Plum (Offer 1)": "Beauty",
    "Plum (Offer 2)": "Beauty",
    "Snitch (Offer 2)": "Fashion",
    "Meolaa": "Fashion",
    "Arrow": "Fashion",
    "Flying Machine": "Fashion",
    "Aeropostale": "Fashion",
    "Donuts": "Food",
    "Ruggers": "Fashion",
    "Colt": "Fashion",
    "Karigari": "Home & Decor",
    "Anahi": "Fashion",
    "Sugr": "Food",
    "Homcentre (Offer 2)": "Home & Decor",
    "Happilo": "Food",
    "Myntra (Offer 1)": "Fashion",
    "Myntra (Offer 2)": "Fashion",
    "Myntra (Offer 3)": "Fashion",
    "Codingal": "Education",
    "The Moms Co": "Personal Care",
    "Mirraw": "Fashion",
    "Fable Street": "Fashion",
    "Pink Fort": "Fashion",
    "March Jewellery": "Jewelry",
    "Healthifyme": "Health & Fitness",
    "Nutrabay": "Health & Wellness",
    "Howard Johnson": "Hospitality",
    "Bhairavgarh Palace": "Hospitality",
    "Zooboo": "Entertainment",
    "Mojo Bar": "Food",
    "Rentomojo": "Rental Services",
    "Dot & Key": "Personal Care",
    "Mcdelivery (Offer 1)": "Food",
    "Mcdelivery (Offer 2)": "Food",
    "Mcdelivery (Offer 3)": "Food",
    "Mcdelivery (Offer 4)": "Food",
    "Bewakoof": "Fashion",
    "Zee5": "Entertainment",
    "Foxtale": "Entertainment",
    "Kiro Beauty": "Personal Care",
    "Juicy Chemistry": "Personal Care",
    "Amazon Shopping Voucher": "Retail",
    "Archies Gallery": "Gifts",
    "Armani Exchange-Luxe Gift Card": "Fashion",
    "Arrow": "Fashion",
    "Aurelia": "Fashion",
    "Balenzia": "Fashion",
    "Bata": "Fashion",
    "Bewakoof": "Fashion",
    "Bluestone Diamond": "Jewelry",
    "Bluestone Gold Jewellery": "Jewelry",
    "Bobbi Brown": "Beauty",
    "Brooks Brothers -Luxe Gift Card": "Fashion",
    "Campus": "Fashion",
    "Candere Diamond Jewellery": "Jewelry",
    "Candere Gold Jewellery": "Jewelry",
    "Celio": "Fashion",
    "Chumbak": "Lifestyle",
    "Decathlon": "Sports & Fitness",
    "Dune-Luxe Gift Card": "Fashion",
    "Elleven": "Fashion",
    "Estele": "Fashion",
    "Euphoria Jewellery Gold Coin": "Jewelry",
    "Euphoria Jewellery Silver Coin": "Jewelry",
    "Fabindia": "Fashion",
    "Fashion Factory": "Fashion",
    "Fastrack Bags": "Fashion",
    "Flipkart": "Retail",
    "Freecultr": "Fashion",
    "G-Star-Luxe Gift Card": "Fashion",
    "Gas-Luxe Gift Card": "Fashion",
    "Gini & Jony": "Kids",
    "Giva": "Gifts",
    "Grt Jewellers": "Jewelry",
    "Hamleys-Luxe Gift Card": "Toys & Games",
    "Helios": "Fashion",
    "Hidesign": "Fashion",
    "Hush Puppies": "Fashion",
    "Jack & Jones": "Fashion",
    "Jockey": "Fashion",
    "Kalyan Diamond Jewellery": "Jewelry",
    "Kalyan Gold Jewellery": "Jewelry",
    "Ketan Diamonds Gold Coin": "Jewelry",
    "Kiehls": "Beauty",
    "Levis": "Fashion",
    "Lifestyle Online": "Retail",
    "Love Beauty & Planet": "Personal Care",
    "Luxe Gift Card": "Gifts",
    "Max": "Fashion",
    "Max Online": "Fashion",
    "Mothercare-Luxe Gift Card": "Kids",
    "Nykaa": "Beauty",
    "Nykaa Fashion": "Fashion",
    "Nykaa Man": "Fashion",
    "Only": "Fashion",
    "Pantaloons": "Fashion",
    "Pc Jeweller Diamond": "Jewelry",
    "Pc Jeweller Gold": "Jewelry",
    "Puma": "Fashion",
    "Relaxo": "Fashion",
    "Reliance Jewels": "Jewelry",
    "Reliance Smart": "Retail",
    "Reliance Smart Point": "Retail",
    "Reliance Trends": "Fashion",
    "Reliance Trends Footwear": "Fashion",
    "Replay- Luxe Gift Card": "Fashion",
    "Shiv Naresh": "Fashion",
    "Shoppers Stop": "Retail",
    "Simple": "Personal Care",
    "Skechers": "Fashion",
    "Skinn": "Fashion",
    "Spencer'S Retail": "Retail",
    "Steve Madden-Luxe Gift Card": "Fashion",
    "Superdry-Luxe Gift Card": "Fashion",
    "Tata Cliq": "Fashion",
    "Tata Cliq Luxury": "Fashion",
    "Tata Cliq Palette": "Fashion",
    "Tego": "Fashion",
    "The Body Shop": "Beauty",
    "mCaffeine":"Beauty",
    "Snitch (Offer 1)":"Fashion",
    "The Raymond Shop": "Fashion",
    "Titan Minimals": "Fashion",
    "Unlimited": "Fashion",
    "V Mart": "Fashion",
    "Veromoda": "Fashion",
    "W": "Fashion",
    "Wildcraft": "Fashion",
    "William Penn": "Stationery",
    "Woggles": "Fashion",
    "Woodland": "Fashion",
    "American Tourister": "Fashion",
    "Assembly": "Fashion",
    "Fab Hotels": "Hospitality",
    "GoStops":"Hospitality",
    "Intermiles": "Travel",
    "Irctc": "Travel",
    "Makemytrip E-Pay": "Travel",
    "Makemytrip Holiday E-Pay": "Travel",
    "Makemytrip Hotel E-Pay": "Travel",
    "Ola Cabs": "Transportation",
    "Points For Good": "Rewards",
    "Samsonite": "Fashion",
    "Taj Experiences": "Hospitality",
    "Uber": "Transportation",
    "Yatra.Com": "Travel",
    "Amazon": "Retail",
    "Amazon Fresh": "Retail",
    "Apollo Pharmacy": "Healthcare",
    "Auric": "Fashion",
    "Avast": "Software",
    "Bakingo": "Food",
    "Bigbasket": "Food & Grocery",
    "Black + Decker": "Home & Garden",
    "Braingymjr": "Toys & Games",
    "Chicago Pizza": "Food",
    "Corseca": "Electronics",
    "Croma": "Electronics",
    "Daily Objects": "Accessories",
    "Discovery Plus": "Entertainment",
    "Docubay": "Entertainment",
    "Finusmart Easy Cash": "Finance",
    "Fitpass": "Health & Fitness",
    "Flower Aura": "Gifts",
    "Gnc": "Health & Wellness",
    "Hammer": "Fitness Equipment",
    "Healthians": "Healthcare",
    "Healthifyme Smart Plan": "Health & Fitness",
    "Hoichoi": "Entertainment",
    "Home Centre Online": "Home & Decor",
    "Mamaearth": "Personal Care",
    "Muthoot Gold Voucher": "Finance",
    "Mx Player": "Entertainment",
    "Myupchar Medicines": "Healthcare",
    "Organic India": "Health & Wellness",
    "Pvr": "Entertainment",
    "Renee Cosmetics": "Beauty",
    "Smile Foundation": "Charity",
    "Sonyliv": "Entertainment",
    "Superbottoms": "Baby Products",
    "Swiggy Money Voucher": "Food",
    "Swiss Beauty": "Beauty",
    "The Skin Story": "Beauty",
    "Veridicus": "Fashion",
    "Vrott": "Fashion",
    "Wonderchef": "Home & Kitchen",
    "Zomato Gift Card": "Food",
    "Et Prime Subscription": "Subscription",
    "Barbeque Nation": "Food",
    "Baskin Robbins": "Food",
    "Beer Cafe": "Food & Beverage",
    "Cafe Delhi Heights": "Food & Beverage",
    "Costa Coffee": "Food & Beverage",
    "Domino'S Pizza": "Food",
    "Kfc": "Food",
    "Machaan": "Food",
    "Mainland China": "Food",
    "Oh! Calcutta": "Food",
    "Pizza Hut": "Food",
    "Sigree": "Food",
    "Sweet Bengal": "Food",
    "Tgif": "Food & Beverage",
    "Amazon Prime Membership": "Subscription",
    "dpauls travel & tours": "Travel",
    "home centre": "Home & Decor",
    "home stop": "Home & Decor",
    "kama ayurveda": "Health & Wellness",
    "more": "Retail",
    "prestige": "Home & Kitchen",
    "reliance jio mart": "Retail",
    "sleepwell": "Home & Decor",
    "truefitt & hill": "Personal Care",
    "reliance digital": "Electronics",
    "reliance my jio store": "Retail",
    "vijay sales": "Electronics"
}




def get_soup(url):
    response = requests.get(url)
    if response.status_code == 200:
        # Parse the HTML content of the page
        soup = BeautifulSoup(response.content, "html.parser")
        return soup
    else:
        return None
